---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "discovery-cron-job-refresh-course-metadata"
  namespace: "{{ K8S_NAMESPACE }}"
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: "discovery-refresh-course-metadata"
              image: "{{ DISCOVERY_DOCKER_IMAGE }}"
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - python ./manage.py refresh_course_metadata --partner openedx
              volumeMounts:
                - mountPath: /openedx/discovery/course_discovery/settings/tutor/production.py
                  name: settings
                  subPath: production.py
          restartPolicy: Never
          volumes:
            - name: settings
              configMap:
                name: discovery-settings
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "credentials-cron-job-copy-catalog"
  namespace: "{{ K8S_NAMESPACE }}"
spec:
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: "credentials-copy-catalog"
              image: "{{ CREDENTIALS_DOCKER_IMAGE }}"
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - python ./manage.py copy_catalog
              volumeMounts:
                - mountPath: /openedx/credentials/credentials/settings/tutor/production.py
                  name: settings
                  subPath: production.py
          restartPolicy: Never
          volumes:
            - name: settings
              configMap:
                name: credentials-settings
